apiVersion: v1
kind: ServiceAccount
metadata:
  name: greatwall-console
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: greatwall-console
subjects:
  - kind: ServiceAccount
    name: greatwall-console
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
